//参考书目《当sketchup遇见ruby》

//用ruby程序在sketchup中绘制一条直线
mod = Sketchup.active_model
ent = mod.entities # All entities in model
sel = mod.selection # Current selection

ent.add_line [0,0,0,],[9,9,9]


//在ruby中绘制一个五角星
mod = Sketchup.active_model # Open model
ent = mod.entities # All entities in model
sel = mod.selection # Current selection

=begin
  #上面三行是Ruby code Editor 预留的程序，
=end

pt1 = [5,0,0]
pt2 = [1.5625,-4.75,0]
pt3 = [-4.0625,-2.9375,00]
pt4 = [-4.0625,2.9375,0]
pt5 = [1.5625,4.758,0]

ent.add_line pt1,pt2
ent.add_line pt2,pt3
ent.add_line pt3,pt4
ent.add_line pt4,pt5
ent.add_line pt5,pt1

//ruby中注释代码有两种方法，一种是用“#”注释单行代码
//另一种是用 “=begin   =end” 注释一段代码


tips：ruby写好的程序可以保存为.rb格式的文件，可以直接在sketchup中直接调用保存好的文件，（需要注意的是，文件路径是反斜杠，和默认路径相反）


//用add curve 绘制五角星
mod = Sketchup.active_model # Open model
ent = mod.entities # All entities in model

pt1 = [5,0,0]
pt2 = [1.5625,-4.75,0]
pt3 = [-4.0625,-2.9375,0]
pt4 = [-4.0625,2.9375,0]
pt5 = [1.5625,4.758,0]

#指定curve变数接受传回的物件，并绘制图形
curve = ent.add_curve pt1,pt2,pt3,pt4,pt5,pt1

#显示curve的形态及长度
puts "curve是什么？", curve.class
puts "curve的长度？", curve.length

//用circle绘制圆圈



tips 编程过程中如果涉及变量或参数需要加（）
//分别用不同方法绘制多边形
mod = Sketchup.active_model # Open model
ent = mod.entities # All entities in model

normal = [0,0,1]
radius = 2
# 用add_ngon 方法指定6个边线
ent.add_ngon [0,0,0],normal,radius, 6

#用add_circle方法指定6个线段
ent.add_circle([5,0,0],normal,radius,6)

#用add_ngon方法指定24条边线
ent.add_ngon [10,0,0],normal,radius, 24

#用add_circle方法指定24条线段（线段数量可省略）
ent.add_circle [15,0,0],normal,radius
